CREATE TABLE IF NOT EXISTS Role (
  RoleID INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(50) UNIQUE NOT NULL,
  Description VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `User` (
  UserID INT AUTO_INCREMENT PRIMARY KEY,
  Username VARCHAR(100) UNIQUE NOT NULL,
  PasswordHash VARCHAR(255) NOT NULL,
  FullName VARCHAR(150),
  Email VARCHAR(150),
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS UserRole (
  UserRoleID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  RoleID INT NOT NULL,
  FOREIGN KEY (UserID) REFERENCES `User`(UserID) ON DELETE CASCADE,
  FOREIGN KEY (RoleID) REFERENCES Role(RoleID) ON DELETE CASCADE
) ENGINE=InnoDB;