CREATE DATABASE IF NOT EXISTS disciplinary;
USE disciplinary;

CREATE TABLE IF NOT EXISTS Student (
  StudentID INT AUTO_INCREMENT PRIMARY KEY,
  EnrollmentNo VARCHAR(50) UNIQUE NOT NULL,
  FirstName VARCHAR(100) NOT NULL,
  LastName VARCHAR(100) NOT NULL,
  DOB DATE,
  Gender ENUM('M','F','Other'),
  Email VARCHAR(150),
  Phone VARCHAR(50),
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Staff (
  StaffID INT AUTO_INCREMENT PRIMARY KEY,
  StaffNo VARCHAR(50) UNIQUE NOT NULL,
  Name VARCHAR(150) NOT NULL,
  Role VARCHAR(100),
  Email VARCHAR(150),
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS OffenseType (
  OffenseTypeID INT AUTO_INCREMENT PRIMARY KEY,
  Code VARCHAR(20) UNIQUE NOT NULL,
  Description VARCHAR(255) NOT NULL,
  SeverityLevel TINYINT NOT NULL,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS IncidentReport (
  IncidentID INT AUTO_INCREMENT PRIMARY KEY,
  ReportDate DATETIME NOT NULL,
  Location VARCHAR(200),
  ReporterStaffID INT,
  StudentID INT NOT NULL,
  Description TEXT,
  Status ENUM('Open','Under Review','Actioned','Closed') DEFAULT 'Open',
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ReporterStaffID) REFERENCES Staff(StaffID) ON DELETE SET NULL,
  FOREIGN KEY (StudentID) REFERENCES Student(StudentID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ReportOffense (
  ReportOffenseID INT AUTO_INCREMENT PRIMARY KEY,
  IncidentID INT NOT NULL,
  OffenseTypeID INT NOT NULL,
  Notes VARCHAR(500),
  FOREIGN KEY (IncidentID) REFERENCES IncidentReport(IncidentID) ON DELETE CASCADE,
  FOREIGN KEY (OffenseTypeID) REFERENCES OffenseType(OffenseTypeID) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS DisciplinaryAction (
  ActionID INT AUTO_INCREMENT PRIMARY KEY,
  IncidentID INT NOT NULL,
  ActionType VARCHAR(100) NOT NULL,
  ActionDate DATE NOT NULL,
  DurationDays INT DEFAULT 0,
  DecisionMakerID INT,
  Notes TEXT,
  FOREIGN KEY (IncidentID) REFERENCES IncidentReport(IncidentID) ON DELETE CASCADE,
  FOREIGN KEY (DecisionMakerID) REFERENCES Staff(StaffID) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Hearing (
  HearingID INT AUTO_INCREMENT PRIMARY KEY,
  IncidentID INT NOT NULL,
  HearingDate DATETIME,
  Outcome VARCHAR(200),
  HearingNotes TEXT,
  FOREIGN KEY (IncidentID) REFERENCES IncidentReport(IncidentID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Appeal (
  AppealID INT AUTO_INCREMENT PRIMARY KEY,
  IncidentID INT NOT NULL,
  AppealDate DATETIME NOT NULL,
  AppealStatus ENUM('Pending','Rejected','Accepted') DEFAULT 'Pending',
  Outcome TEXT,
  FOREIGN KEY (IncidentID) REFERENCES IncidentReport(IncidentID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Attachment (
  AttachmentID INT AUTO_INCREMENT PRIMARY KEY,
  IncidentID INT NOT NULL,
  FileName VARCHAR(255),
  FilePath VARCHAR(512),
  UploadedBy INT,
  UploadDate DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (IncidentID) REFERENCES IncidentReport(IncidentID) ON DELETE CASCADE,
  FOREIGN KEY (UploadedBy) REFERENCES Staff(StaffID) ON DELETE SET NULL
) ENGINE=InnoDB;